import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Box, Paper, Typography } from '@mui/material'
import BreadCrumbs from '@/components/ui/Breadcumbs'
import SignUp from '@/components/ui/signup'
import ButtonAppBarLogin from '@/components/NavbarLogin'
import Footer from '@/components/ui/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Paper >
      <Box>
      <ButtonAppBarLogin/>
      </Box>
      <Box>
        <SignUp/>
      </Box>

      </Paper>
      <Footer/>
      
    </>
  )
}