import Head from 'next/head'
import ButtonAppBar from '@/components/Navbar';
import { Box, Paper } from '@mui/material';
import { useSession } from "next-auth/react";
import BreadCrumbs from '@/components/ui/Breadcumbs';
import Footer from '@/components/ui/footer';
export default function product() {
  const { data: session, status } = useSession();

  console.log(session);

  if (!session) {
    return (
      <>
        <Head>
          <title>Acerca de</title>
        </Head>
        <Paper>
          <h1 align='center'>Acceso denegado</h1>
        </Paper>
      </>
    )
  }
  
    return (
      <>
       
        <Head>
            <title>Productos</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
       
      <Paper>
      <Box>
      <ButtonAppBar/>
      </Box>
      <div sx={{marginBottom: 3,marginTop: 5}}>
        <BreadCrumbs/>
      </div>
      <h1>Hola</h1>
      </Paper>
      <Footer/>
      </>
    )
  }
