import Head from 'next/head';
import { useRouter} from 'next/router';
import { useEffect, useState } from 'react';
import apiClient from '@/apiClient';
import { Box, Container, FormControl, Grid, InputLabel, MenuItem, Paper, Select, TextField, Typography } from '@mui/material';
import MediaCard from '@/components/ui/productCard';
import Swal from 'sweetalert2';
import ButtonAppBar from '@/components/Navbar';
import BreadCrumbs from '@/components/ui/Breadcumbs';
import Gallery from '@/components/ui/Gallery';
import { useSession } from "next-auth/react";
import Footer from '@/components/ui/footer';

export default function Product() {
    const { data: session, status } = useSession();
    const router = useRouter();
    const [product, setProduct] = useState(undefined);
    
    console.log(session);

    useEffect(() => {
        if(router.query?.slug) {
        apiClient.get(`/api/products/${router.query.slug}`)
        .then((response) => {
            console.log(response.data)
            setProduct(response.data);
        })
        .catch((error) => {
            console.log(error);
            //alert('Error');
        });
    }
    }, [router]);
    

    if (!session) {
      return (
        <>
          <Head>
            <title>Acerca de</title>
          </Head>
          <Paper>
            <h1 align='center'>Acceso denegado</h1>
          </Paper>
        </>
      )
    }
  



    return (
    <>
        <Head>
            <title>Producto-info</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <Paper>
        <Box>
            <ButtonAppBar/>
        </Box>
            <Container>
                <Typography variant='h4'>Infromación del Producto: {product?.name}</Typography>
                <Typography>Galería</Typography>
                {product && product?.gallery && (
                    <Gallery 
                        basePath="http://localhost:3000/api/documents/view?file="
                        gallery={product.gallery}
                        width={750}
                        height={550}
                    />
                )}
            </Container>
        </Paper>
        <Footer/>
     </>
    )
}