import * as React from 'react';
import Head from 'next/head';
import { Inter } from '@next/font/google';
import ButtonAppBar from '@/components/Navbar';
import { Box, Container, Link, Paper, Typography } from '@mui/material';
import BreadCrumbs from '@/components/ui/Breadcumbs';
import { useSession } from "next-auth/react";
import Footer from '@/components/ui/footer';
import useMediaQuery from '@mui/material/useMediaQuery';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data: session, status } = useSession();
  console.log(session);

  /* const prefersDarkMode = useMediaQuery('(prefers-color-scheme: dark)');

  const theme = React.useMemo(
    () =>
      createTheme({
        palette: {
          mode: prefersDarkMode ? 'dark' : 'light',
        },
      }),
    [prefersDarkMode],
  ); */

  if (!session) {
    return (
      <>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Paper>
      <Box>
      <ButtonAppBar/>
      </Box>
        <Container>
      <Box>
        <Typography variant="h1" component="div" align='center'>
          Hola Bienvenido
        </Typography>
      </Box>
      </Container>
      
      </Paper>
      <Footer/>
    </>
    )
  }

  return (
    <>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Paper>
      <Box>
      <ButtonAppBar/>
      </Box>
      <div sx={{marginBottom: 3,marginTop: 5}}>
        <BreadCrumbs/>
      </div>
      <Box>
        <Typography variant="h1" component="div" align='center'>
          Hola Bienvenido
        </Typography>
      </Box>
      
      </Paper>
      <Footer/>
    </>
  )
}

